[package]
name = "sentry"
version = "0.1.0"
authors = ["Rasmus Viitanen <rasmus.viitanen@configura.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sentry = { version = "0.22.0", features = ["panic"] }